### ISSUE TITLE
Artboards are overlapping if it's not the first page of Sketch document

### ISSUE THREAD

**Issue by ejdelmonico** [tadija/AEIconizer#19] opened 2016-08-21 18:18 UTC
I just installed current version of plugin into Sketch 39.1. I have an icon artboard sized at 1024 x 1024. I selected it and ran the plugin. All artwork is created but groups ar on top of each other. They are exported that way as well.

**Comment by tadija** [comment] 2016-08-21 18:20
It works for me in same version, make sure you're on the latest version of plugin, and also from some weird reason it works just on "Page 1" of a new Sketch document, maybe that's problem?

**Comment by ejdelmonico** [comment] 2016-08-21 18:45
Ahh, maybe that is it. I was using it on page 2. When I use it next, I will see if that is the issue. Thank you.

**Comment by johnborges** [comment] 2016-09-30 15:24
Anyone confirm if this is fixed? I'm encountering the same issue regardless of what page I'm on.
Sketch 40.1
AEIconizer 2.2.2

**Comment by iign** [comment] 2016-11-16 20:15
I can confirm the same issue is still happening. 
Using Sketch 41.
:/

**Comment by tadija** [comment] 2016-11-20 20:42
I tested now again and plugin still works normally in Sketch 41, if it's on the first page of Sketch document. Any other page makes this issue happen, and if someone has a solution for that bug please say here or make a pull request.

**Comment by iign** [comment] 2016-11-20 21:13
For what it's worth, I can reproduce the issue whenever I duplicate a page and run the plugin. Doesn't matter if it's the first page.

**Comment by tadija** [comment] 2017-06-07 22:28
This should be fixed now in the latest version (2.3.0).

**Closed by tadija** 2017-06-07 22:28 UTC
