### ISSUE TITLE
Artboards are in wrong position if run on other than first page.

### ISSUE THREAD

**Issue by rdoyle720** [tadija/AEIconizer#25] opened 2016-11-17 19:51 UTC
If I run the plugin on my first page in the Sketch file, everything works fine. If I create an additional page in the same file and run it there, all the artboards will be positioned randomly and overlap each other.
![screen shot 2016-11-17 at 1 51 34 pm](https://cloud.githubusercontent.com/assets/5444526/20405016/faa50c4c-accc-11e6-9073-70ef699723e0.png)

**Comment by tadija** [comment] 2016-11-20 20:43
Thanks for reporting, I will close this as it's duplicate of #19.

**Closed by tadija** 2016-11-20 20:43 UTC
